name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install poetry
      run: |
        make download-poetry
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-interaction

    - name: Run safety checks
      run: STRICT=1 make check-safety

    - name: Run style checks
      run: STRICT=1 make check-style

    - name: Run tests
      run: make test
